### Обязательные библиотеки:
- [Gensim](https://radimrehurek.com/gensim/) — инструмент для решения различных задач NLP (тематическое моделирование, представление текстов, ...);
- [Numpy](http://www.numpy.org) — библиотека для векторных вычислений;
Для выполнения дополнительных заданий (по желанию)
- [Pandas](https://pandas.pydata.org) - библиотека для анализа табличных данных;
- [scikit-learn](http://scikit-learn.org/stable/index.html) — библилиотека с алгоритмами классического машинного обучения;
- [matplotlib](https://matplotlib.org) - библиотека для построения графиков;

-------

In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd

# Константы
DATA_DIR = 'data'
RANDOM_STATE = 42

### Модель, генерирующая вектора слов

In [2]:
from utils import download_model

download_model(data_dir=DATA_DIR)

Скачиваем архив из http://vectors.nlpl.eu/repository/20/213.zip...
Архив успешно скачан
Распаковываем архив...
Архив успешно распакован


In [3]:
import gensim

wv_embeddings = gensim.models.fasttext.FastTextKeyedVectors.load(
    DATA_DIR + "/model/model.model"
)

In [4]:
wv_embeddings['студент']

array([-0.12469783,  0.18736716,  0.22868113,  0.27407894,  0.05341857,
        0.1317426 , -0.33944902,  0.15010178,  0.11839966, -0.05448272,
       -0.04013713,  0.19393396,  0.05723746, -0.28904027,  0.29126135,
       -0.03872602,  0.05806026, -0.1647555 ,  0.2963717 , -0.2940837 ,
       -0.01341213,  0.06515279, -0.28850263,  0.18423478,  0.12815852,
        0.10678071,  0.28139436,  0.00773022, -0.11348739,  0.14297695,
       -0.26492628, -0.129977  ,  0.07842775, -0.02894384, -0.20529068,
       -0.21005282, -0.30868313, -0.0292949 , -0.07670937, -0.26449117,
       -0.3972074 , -0.17982467,  0.13768162, -0.00637981,  0.28404418,
        0.12720445, -0.0358741 ,  0.02867263, -0.06640667,  0.04235253,
       -0.08003537, -0.13680768,  0.05537779, -0.09530751,  0.06231942,
        0.06368092, -0.08036334, -0.01808719,  0.2860434 , -0.06926312,
        0.0442103 ,  0.13214391,  0.04134564, -0.08806223,  0.05270072,
        0.19283819, -0.3059145 ,  0.41431952,  0.11099023, -0.42

In [5]:
emb = np.array(wv_embeddings['студент'])
emb /= np.linalg.norm(emb)
emb


array([-0.03489639,  0.05243425,  0.06399587,  0.07670034,  0.01494906,
        0.03686785, -0.094994  ,  0.04200562,  0.03313386, -0.01524686,
       -0.01123228,  0.05427196,  0.01601777, -0.08088723,  0.08150879,
       -0.01083738,  0.01624803, -0.04610643,  0.08293891, -0.08229863,
       -0.00375335,  0.01823285, -0.08073677,  0.05155766,  0.03586486,
        0.02988233,  0.07874754,  0.00216328, -0.03175918,  0.04001176,
       -0.07413899, -0.03637375,  0.02194782, -0.00809987, -0.0574501 ,
       -0.05878278, -0.08638424, -0.00819811, -0.02146693, -0.07401723,
       -0.11115754, -0.0503235 ,  0.03852987, -0.00178538,  0.07948908,
        0.03559786, -0.01003928,  0.00802397, -0.01858375,  0.01185225,
       -0.02239771, -0.0382853 ,  0.01549734, -0.02667158,  0.01743994,
        0.01782095, -0.02248949, -0.00506166,  0.08004856, -0.01938312,
        0.01237215,  0.03698016,  0.01157048, -0.024644  ,  0.01474817,
        0.05396531, -0.08560944,  0.11594633,  0.03106035, -0.11

In [6]:
emb = np.array(wv_embeddings['картофелина'])
emb /= np.linalg.norm(emb)
emb


array([-0.03565654, -0.03829435, -0.07473019, -0.03133808,  0.04485418,
        0.07308763, -0.1029348 , -0.00892474,  0.0128747 , -0.00847647,
       -0.01244493,  0.03711125, -0.04288177,  0.09699574, -0.02891883,
        0.06490687,  0.02554925, -0.04276988, -0.07115022,  0.03140735,
        0.04430457, -0.02939145, -0.01895241, -0.03690491, -0.06630892,
        0.04586839,  0.03821316,  0.06454388,  0.06004666, -0.02356774,
       -0.02259666,  0.01798983, -0.00159842,  0.0551695 ,  0.01586303,
       -0.12098493, -0.00806889,  0.10303804, -0.02125984,  0.04219737,
       -0.08073614,  0.03812043, -0.08584967,  0.02181023,  0.09533481,
       -0.07798886,  0.03180066, -0.00612879, -0.04050269,  0.02436995,
        0.03135969,  0.00458921, -0.05318176,  0.06151418,  0.0715723 ,
        0.05001796, -0.02099234, -0.00224496,  0.08405922, -0.05100806,
       -0.01792019,  0.11412664,  0.06918405,  0.04646955, -0.01340511,
        0.00524455,  0.06360761, -0.02500637, -0.01569892,  0.01

In [7]:
emb = np.array(wv_embeddings['!+3;йц'])
emb /= np.linalg.norm(emb)
emb


array([-4.55330638e-03, -4.54042964e-02,  6.75861090e-02, -8.08979571e-03,
        7.01731071e-02,  3.47747020e-02, -3.30218039e-02, -3.81388143e-02,
        6.20581880e-02, -6.40948415e-02, -1.20337252e-02, -7.47386217e-02,
       -3.13442536e-02,  6.06456958e-02,  3.24464738e-02, -1.26370769e-02,
       -8.70469138e-02, -4.60836804e-03, -4.96385247e-02, -9.91586316e-03,
       -3.26424614e-02, -7.82137513e-02,  1.35636255e-01, -2.07703356e-02,
        6.84733270e-03, -1.67997964e-02,  5.86115085e-02, -1.11853607e-01,
        9.05701071e-02,  1.48371570e-02,  4.80151735e-02, -9.49617010e-03,
        6.27528876e-03,  2.62407283e-03,  9.65024382e-02, -2.33389828e-02,
        3.01020965e-02,  2.98880804e-02, -6.94328323e-02, -2.77445335e-02,
       -9.98459011e-02,  1.77633192e-03, -4.10710052e-02, -3.61414365e-02,
        1.25337526e-01, -1.08477376e-01, -2.32283287e-02, -8.18958506e-02,
        4.64944765e-02,  1.37787051e-02, -2.09058952e-02, -4.57360260e-02,
        1.30667940e-01,  

In [15]:
wv_embeddings.most_similar_to_given('музыка', ['вода', 'стол', 'рюкзак', 'мышь', '!+!wd'] )

'стол'

In [9]:
many_meaning_word = wv_embeddings.most_similar( 'модель', topn=25)
many_meaning_word


[('модел', 0.6967176795005798),
 ('модификация', 0.6914131045341492),
 ('модели', 0.678629457950592),
 ('моделька', 0.6424816846847534),
 ('моделек', 0.6388702392578125),
 ('модельный', 0.6084722876548767),
 ('концепт', 0.6072477102279663),
 ('прототип', 0.5757204294204712),
 ('линейка', 0.5752154588699341),
 ('-модель', 0.5710797905921936),
 ('формфактор', 0.5630917549133301),
 ('функциональной', 0.5625118613243103),
 ('марка', 0.5573339462280273),
 ('пальтопроизводитель', 0.5564113855361938),
 ('конструироваться', 0.5550590753555298),
 ('модернизированный', 0.5542082190513611),
 ('бизнес-модель', 0.5539443492889404),
 ('модификацие', 0.5506161451339722),
 ('флагманский', 0.5501906275749207),
 ('7модель', 0.5499307513237),
 ('усовершенствованный', 0.5498217344284058),
 ('высокопроизводительной', 0.5465802550315857),
 ('функционаленный', 0.5452821254730225),
 ('устройство', 0.5437973737716675),
 ('компоновка', 0.543060302734375)]

In [10]:
many_meaning_word = wv_embeddings.most_similar( 'картофелина', topn=25)
many_meaning_word


[('морковь', 0.7455145120620728),
 ('морковка', 0.7360334992408752),
 ('картофель', 0.7326324582099915),
 ('репчатый', 0.7247191667556763),
 ('ломтик', 0.7246931791305542),
 ('брусочка', 0.7208032011985779),
 ('долька', 0.7206475138664246),
 ('помидор', 0.7119176983833313),
 ('зубчик', 0.7092844843864441),
 ('помидорка', 0.7086368203163147),
 ('картошка', 0.6999233365058899),
 ('нарезать', 0.6964611411094666),
 ('порежьт', 0.6940442323684692),
 ('отварить', 0.6917652487754822),
 ('порежлять', 0.6905490756034851),
 ('нарежь', 0.6904594898223877),
 ('стручок', 0.6899489760398865),
 ('свекла', 0.6891882419586182),
 ('кабачок', 0.6879203915596008),
 ('зубчиков', 0.6877299547195435),
 ('натертый', 0.686590313911438),
 ('нарежьт', 0.6857255697250366),
 ('клубень', 0.6832814812660217),
 ('нашинковать', 0.6829817891120911),
 ('нарежлять', 0.6826160550117493)]

In [11]:
many_meaning_word = wv_embeddings.most_similar( '!+3;йц', topn=25)
many_meaning_word


[('статистика', 0.34109941124916077),
 ('статистик', 0.3388494849205017),
 ('статистический', 0.32298538088798523),
 ('нацстатк', 0.32211723923683167),
 ('шашни', 0.3205094337463379),
 ('артистичный', 0.31432417035102844),
 ('неряха', 0.31332021951675415),
 ('среднестатистический', 0.3029423654079437),
 ('артистизм', 0.3010713458061218),
 ('анкетный', 0.29532888531684875),
 ('статистически', 0.292111337184906),
 ('выданье', 0.2867397665977478),
 ('скупердяй', 0.2847190797328949),
 ('анамнез', 0.28284314274787903),
 ('неженатый', 0.2795346975326538),
 ('артистично', 0.279416561126709),
 ('белстат', 0.27742287516593933),
 ('англичанка', 0.2762793302536011),
 ('личное', 0.27514779567718506),
 ('лоботряс', 0.2748919725418091),
 ('зпр', 0.2747698426246643),
 ('оболтус', 0.2735040783882141),
 ('шпынять', 0.2706041634082794),
 ('алкоголичка', 0.26663708686828613),
 ('донжуан', 0.2663349509239197)]

In [12]:
many_meaning_word = wv_embeddings.most_similar( 'чета', topn=25)
many_meaning_word


[('супруга', 0.6289085149765015),
 ('семья', 0.6149129271507263),
 ('монарший', 0.5840944647789001),
 ('особа', 0.5785672068595886),
 ('супруг', 0.5743242502212524),
 ('правнука', 0.5739880204200745),
 ('чет', 0.5713399052619934),
 ('жена', 0.5665680170059204),
 ('родственник', 0.563919186592102),
 ('супружеский', 0.5607016086578369),
 ('родственница', 0.5599842071533203),
 ('новобрачный', 0.5594439506530762),
 ('бездетный', 0.5536180734634399),
 ('аристократ', 0.5517197251319885),
 ('родня', 0.5450208187103271),
 ('вдова', 0.5417022109031677),
 ('августейший', 0.5414412021636963),
 ('вдовствовать', 0.5398431420326233),
 ('пар', 0.5360672473907471),
 ('кузен', 0.5360124111175537),
 ('супружество', 0.5343000292778015),
 ('барон', 0.5341541767120361),
 ('семейка', 0.5322067141532898),
 ('вдовство', 0.5317885279655457),
 ('отец', 0.5304945707321167)]

In [13]:
many_meaning_word = wv_embeddings.most_similar( 'кринж', topn=25)
many_meaning_word


[('криница', 0.5920141935348511),
 ('кринолин', 0.4786418676376343),
 ('инж', 0.47224166989326477),
 ('плюмаж', 0.4381290376186371),
 ('песочник', 0.4344562590122223),
 ('коктейльной', 0.4231693148612976),
 ('горлица', 0.4161262810230255),
 ('вуокс', 0.4158424437046051),
 ('лазоревый', 0.41280657052993774),
 ('-бабочка', 0.41049686074256897),
 ('арагви', 0.4095531702041626),
 ('демерджи', 0.4090195596218109),
 ('мехи', 0.40718168020248413),
 ('капри', 0.4056819975376129),
 ('иордань', 0.40479716658592224),
 ('фрак', 0.4032813608646393),
 ('кираса', 0.40200090408325195),
 ('камзол', 0.40127506852149963),
 ('бородача', 0.4006243348121643),
 ('черепаховый', 0.4000708758831024),
 ('парусиновый', 0.39899662137031555),
 ('скафандр', 0.39763638377189636),
 ('мухавец', 0.3963255286216736),
 ('галун', 0.3958277106285095),
 ('купальщик', 0.3945847749710083)]

In [16]:
wv_embeddings.most_similar([ 'вычисления', 'математика','кибернетика', 'информатика'],['физика','химия', 'биология'])

[('вычисление', 0.5770097374916077),
 ('вычислительный', 0.5413917303085327),
 ('-вычислительный', 0.5393710732460022),
 ('вычислитель', 0.5220285654067993),
 ('кибернетик', 0.4932546019554138),
 ('алгоритмизация', 0.4776235818862915),
 ('информационный', 0.47564980387687683),
 ('геоинформационный', 0.4712117910385132),
 ('кибербезопасность', 0.4706329107284546),
 ('вычислить', 0.4694153964519501)]

In [17]:
wv_embeddings.doesnt_match(['завтрак', 'обед', 'ужин', 'студент'])

'студент'

In [18]:
wv_embeddings.doesnt_match(['завтрак', 'обед', 'ужин'])

'завтрак'